FROM python:3.9-slim

WORKDIR /app

RUN pip install --no-cache-dir requests

# Copy the current directory contents into the container at /app
COPY . /app

# Set the logging level (1 for basic logging)
ENV LOG=1

# Run authorization.py when the container launches
CMD ["python", "authorization.py"]